apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-assistant-settings
  namespace: argocd
data:
  settings.js: |
    var argocdAssistantSettings = {
        provider: "Llama-Stack-V2",
        model: "azure/gpt-4o-mini"
    };
    (() => {
        console.log("Initializing Argo CD Assistant Settings");
        console.log(globalThis.argocdAssistantSettings);
    })();
