apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-assistant-settings
  namespace: argocd
data:
  settings.js: |
    var argocdAssistantSettings = {
        provider: "Llama-Stack-V2",
        baseUrl: "http://llamastack.llamastack.svc.cluster.local:8321/v1/openai/v1",
        model: "llamastack"
    };